#!/usr/bin/env ruby

require_relative 'lib/directed_acyclic_graph.rb'
require_relative 'app/helpers.rb'

case ARGV.first
when nil then 
  raise ArgumentError, "Error: No argument provided"
when 'test' then 
  require_relative 'test/scheduler_test'
  test_suite
else 
  puts file_to_dag(ARGV[0]).topological_sort
end
